# Site wide configuration

title: pH-BB - Präzise Kalkung in Brandenburg 
locale: en_US
description: Ein EIP-Agrar Projekt zur Verbesserung der landwirtschaftlichen Produktivität und Nachhaltigkeit. 
logo: pH-BB.png
url: https://limingprecisionfarming.github.io/soil-lovers/

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

comments: true

# Site owner
owner:
  name: Ingmardo Dos Silva
  avatar: 
  email: ingmardo@mustermann.com
  disqus-shortname: sosimpletheme
  github: LimingPrecisionFarming
  researchgate: 
  google:
    plus: MichaelRoseDesign
    analytics: UA-2011187-2
    verify: UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y
    ad-client: ca-pub-7328585512091257
    ad-slot: 7855747535
  bing-verify: D81F4C18A6CB3018F64D7C827D953DFD
